# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-26 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RTDB', 'RTDB'), ('NDB', 'NDB')], default='RTDB', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintananceWindowHour', models.IntegerField(default=10)),
                ('trafficPercentageUnderMaitananceWindow', models.FloatField(default=1)),
                ('releaseCPUImpact', models.FloatField(default=0.05)),
                ('releaseAppMemoryImpact', models.FloatField(default=0.1)),
                ('releaseDBMemoryImpact', models.FloatField(default=0.1)),
                ('releaseCountCPUImpact', models.FloatField(default=0.05)),
                ('reservedCPURatio', models.FloatField(default=0.15)),
                ('ndbRTDBCostRatio', models.FloatField(default=1.3)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultSIGTRANLinkSpeed', models.IntegerField()),
                ('defaultSIGTRANLinkNumber', models.IntegerField()),
                ('maxSIGTRANPortUtil', models.FloatField()),
            ],
        ),
    ]
