# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-26 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('virtualizationSupported', models.BooleanField(default=True)),
                ('ndbSupported', models.BooleanField(default=True)),
                ('coreNumber', models.IntegerField()),
                ('overallCapacity', models.FloatField()),
                ('singleThreadCapacity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CPUList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpuNumber', models.IntegerField()),
                ('clientNumber', models.IntegerField()),
                ('capacityRatio', models.FloatField()),
                ('mateCapacityNDB', models.IntegerField()),
                ('dbCapacityNDB', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CPUTuning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuningOption', models.CharField(choices=[('Simple', 'Simple'), ('Normal', 'Normal'), ('Aggressive', 'Aggressive')], default='Normal', max_length=16)),
                ('systemCPUUsage', models.FloatField()),
                ('clientCPUUsage', models.FloatField()),
                ('dbMode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.DBMode')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('maxNodeNumber', models.IntegerField()),
                ('maxSubscriberSupport', models.IntegerField()),
                ('vmCapacityRatio', models.FloatField(default=0.8)),
                ('reservedCoreNumberForVM', models.IntegerField(default=0)),
                ('defaultCPUNumber', models.IntegerField()),
                ('defaultClientNumber', models.IntegerField()),
                ('defaultMemory', models.IntegerField()),
                ('maxSIGTRANPerIONode', models.IntegerField()),
                ('maxLDAPPerIONode', models.IntegerField()),
                ('maxDiameterPerIONode', models.IntegerField()),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.CPU')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('isVM', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.IntegerField()),
                ('hardwareModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.HardwareModel')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryUsageTuning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Simple', 'Simple'), ('Normal', 'Normal'), ('Aggressive', 'Aggressive')], default='Normal', max_length=16)),
                ('memoryUsageTuning', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VMType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Native', 'Native'), ('Openstack', 'Openstack'), ('VMWare', 'VMWare'), ('CBIS', 'CBIS')], max_length=16)),
                ('capacity', models.FloatField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='hardwareType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.HardwareType'),
        ),
        migrations.AddField(
            model_name='cputuning',
            name='hardwareType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.HardwareType'),
        ),
        migrations.AddField(
            model_name='cpulist',
            name='hardwareModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.HardwareModel'),
        ),
    ]
