# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-15 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_auto_20171228_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaretype',
            name='isSingleServer',
            field=models.BooleanField(default=False),
        ),
    ]
