# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_calltype_mateupdatesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltype',
            name='isShow',
            field=models.BooleanField(default=True),
        ),
    ]
