# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20171228_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinformation',
            name='aprocCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='applicationinformation',
            name='asCost',
            field=models.FloatField(default=0),
        ),
    ]
