# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20171230_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinformation',
            name='diamCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='applicationinformation',
            name='ss7Cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='applicationinformation',
            name='tcpCost',
            field=models.FloatField(default=0),
        ),
    ]
