# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-20 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_release_countermemoryimpact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAdditionalImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sameSys1GroupLevel1', models.FloatField(default=1)),
                ('sameSys1GroupLevel2', models.FloatField(default=1.15)),
                ('sameSys2GroupLevel1', models.FloatField(default=1.2)),
                ('sameSys2GroupLevel2', models.FloatField(default=1.12)),
                ('diffSys1GroupLevel1', models.FloatField(default=1.3)),
                ('diffSys1GroupLevel2', models.FloatField(default=1.46)),
                ('diffSys2GroupLevel1', models.FloatField(default=1)),
                ('diffSys2GroupLevel2', models.FloatField(default=1.08)),
                ('uncorrelatedCCRUTHandling', models.FloatField(default=0.6)),
            ],
        ),
    ]
