# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20180321_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbname',
            name='isIncludeInactiveSubscriber',
            field=models.BooleanField(default=False, verbose_name='Is Including Inactive Subscriber?'),
        ),
    ]
