# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_dbname_isincludeinactivesubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationname',
            name='needConfigDB',
            field=models.BooleanField(default=False, verbose_name='Need to Config DB?'),
        ),
    ]
