# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-27 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_applicationname_needconfigdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='ndbStopWriteRatio',
            field=models.FloatField(default=0.8),
        ),
    ]
