# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-29 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_release_ndbstopwriteratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltype',
            name='type',
            field=models.CharField(choices=[('Voice', 'Voice'), ('LDAP', 'LDAP'), ('Diameter', 'Diameter')], default='Voice', max_length=30, verbose_name='Type Option'),
        ),
    ]
