# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_calltype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltype',
            name='groupTransactionNumber',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='calltype',
            name='groupTransactionNumber2',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='calltype',
            name='groupTransactionNumber3',
            field=models.IntegerField(default=2),
        ),
    ]
