# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-24 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20180330_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='capacityPerNDBMateVhost',
            field=models.IntegerField(default=15000),
        ),
        migrations.AddField(
            model_name='release',
            name='capacityPerNDBNode',
            field=models.IntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='release',
            name='capacityPerNDBRoutingVhost',
            field=models.IntegerField(default=15000),
        ),
        migrations.AddField(
            model_name='release',
            name='ndbReplicationFactor',
            field=models.IntegerField(default=2),
        ),
    ]
