# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20180424_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='trafficRequireDedicateMate',
            field=models.IntegerField(default=2000),
        ),
    ]
