# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-10 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_dbname_featureimpactfactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbname',
            name='featureImpactFactor',
        ),
        migrations.AddField(
            model_name='dbname',
            name='featureGroupImpactFactor',
            field=models.FloatField(default=0, verbose_name='Feature Group Impact Factor'),
        ),
        migrations.AddField(
            model_name='dbname',
            name='featureMemberImpactFactor',
            field=models.FloatField(default=0, verbose_name='Feature Member Impact Factor'),
        ),
    ]
