# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-15 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_auto_20180510_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbname',
            name='defaultDRouterFactor',
            field=models.FloatField(default=0, verbose_name='Default Factor for DRouter'),
        ),
        migrations.AddField(
            model_name='dbname',
            name='defaultEctrlFactor',
            field=models.FloatField(default=0, verbose_name='Default Factor for ECTRL'),
        ),
        migrations.AddField(
            model_name='dbname',
            name='defaultEppsmFactor',
            field=models.FloatField(default=0, verbose_name='Default Factor for EPPSM'),
        ),
    ]
