# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-26 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appNodeNumber', models.IntegerField(default=0)),
                ('dbNodeNumber', models.IntegerField(default=0)),
                ('ioNodeNumber', models.IntegerField(default=0)),
                ('applicationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ApplicationName', verbose_name='Application Name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'verbose_name': 'Calculated Result',
                'verbose_name_plural': 'Calculated Result',
            },
        ),
        migrations.CreateModel(
            name='DimensioningResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemNumber', models.IntegerField(default=0)),
                ('appNodeNeededNumber', models.IntegerField(default=0)),
                ('dbNodeNeededNumber', models.IntegerField(default=0)),
                ('ioNodeNeededNumber', models.IntegerField(default=0)),
                ('pilotNodeNeededNumber', models.IntegerField(default=0)),
                ('totalNodeNeededNumber', models.IntegerField(default=0)),
                ('averageClientCPUUsage', models.FloatField(default=0)),
                ('dbCacheSize', models.FloatField(default=0)),
                ('totalMemoryUsage', models.FloatField(default=0)),
                ('sigtranSpeed', models.FloatField(default=0)),
                ('ethernetPortsRequiredNumber', models.IntegerField(default=0)),
                ('totalTCPUDPSpeed', models.FloatField(default=0)),
                ('amaRecordNumberPerSecond', models.FloatField(default=0)),
                ('dialyBillingFileSize', models.FloatField(default=0)),
                ('amaRetrieveSpeed', models.FloatField(default=0)),
                ('ladpDiameterUDP', models.FloatField(default=0)),
                ('muSpeed', models.FloatField(default=0)),
                ('memoryUsagePerAppNode', models.FloatField(default=0)),
                ('memoryUsagePerClient', models.FloatField(default=0)),
                ('appNodeMemoryUsagePercent', models.FloatField(default=0)),
                ('pilotSharedDiskSize', models.FloatField(default=0)),
                ('dbDiskSizeForMateUpdate', models.FloatField(default=0)),
                ('diskSizeForDB', models.FloatField(default=0)),
                ('applicationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ApplicationName', verbose_name='Application Name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'verbose_name': 'Dimensioning Result',
                'verbose_name_plural': 'Dimensioning Result',
            },
        ),
        migrations.CreateModel(
            name='DimensioningResultPerSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appNodeNumber', models.IntegerField(default=0)),
                ('dbNodeNumber', models.IntegerField(default=0)),
                ('ioNodeNumber', models.IntegerField(default=2)),
                ('pilotNodeNumber', models.IntegerField(default=2)),
                ('totalNodeNumber', models.IntegerField(default=0)),
                ('averageClientCPUUsage', models.FloatField(default=0)),
                ('dbCacheSize', models.FloatField(default=0)),
                ('totalMemoryUsage', models.FloatField(default=0)),
                ('sigtranSpeed', models.FloatField(default=0)),
                ('totalTCPUDPSpeed', models.FloatField(default=0)),
                ('amaRecordNumberPerSecond', models.FloatField(default=0)),
                ('dialyBillingFileSize', models.FloatField(default=0)),
                ('amaRetrieveSpeed', models.FloatField(default=0)),
                ('ladpDiameterUDP', models.FloatField(default=0)),
                ('muSpeed', models.FloatField(default=0)),
                ('memoryUsagePerAppNode', models.FloatField(default=0)),
                ('memoryUsagePerClient', models.FloatField(default=0)),
                ('appNodeMemoryUsagePercent', models.FloatField(default=0)),
                ('pilotSharedDiskSize', models.FloatField(default=0)),
                ('dbDiskSizeForMateUpdate', models.FloatField(default=0)),
                ('diskSizeForDB', models.FloatField(default=0)),
                ('dimensioningResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.DimensioningResult')),
            ],
            options={
                'verbose_name': 'Dimensioning Result Per System',
                'verbose_name_plural': 'Dimensioning Result Per System',
            },
        ),
    ]
