# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20171227_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficinformation',
            name='inactiveSubscriber',
            field=models.IntegerField(verbose_name='Inactive Subscriber'),
        ),
    ]
