# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20171230_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficinformation',
            name='diamCPUCost',
            field=models.FloatField(default=0),
        ),
    ]
