# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_trafficinformation_diamcpucost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationconfiguration',
            old_name='dbCPUCost',
            new_name='aprocCPUCost',
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='asCPUCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='diamCPUCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='featureSS7InSize',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='featureSS7OutSize',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='groupCounterCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='spaDataSize',
            field=models.IntegerField(default=0),
        ),
    ]
