# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-02 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20180101_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfiguration',
            name='spaDataSize',
            field=models.FloatField(default=0),
        ),
    ]
