# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-02 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_applicationconfiguration_spadatasize'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfiguration',
            name='counterCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='featureCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='featureSS7InSize',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='featureSS7OutSize',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='groupCounterCost',
            field=models.FloatField(default=0),
        ),
    ]
