# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-02 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20180102_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfiguration',
            name='ndbCPULimitation',
            field=models.FloatField(default=0),
        ),
    ]
