# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-14 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20180211_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedresult',
            name='appNodeNumber',
            field=models.IntegerField(default=0, verbose_name='App Node Name'),
        ),
        migrations.AlterField(
            model_name='calculatedresult',
            name='dbNodeNumber',
            field=models.IntegerField(default=0, verbose_name='DB Node Name'),
        ),
        migrations.AlterField(
            model_name='calculatedresult',
            name='ioNodeNumber',
            field=models.IntegerField(default=0, verbose_name='IO Node Name'),
        ),
        migrations.AlterField(
            model_name='calltypecounterconfiguration',
            name='callType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.CallType', verbose_name='Call Type'),
        ),
        migrations.AlterField(
            model_name='dbconfiguration',
            name='cacheSize',
            field=models.IntegerField(default=0, verbose_name='Cache Size (MB)'),
        ),
        migrations.AlterField(
            model_name='dbconfiguration',
            name='mateLogSize',
            field=models.IntegerField(default=0, verbose_name='Mate Log Size (MB)'),
        ),
        migrations.AlterField(
            model_name='dbconfiguration',
            name='memberGroupOption',
            field=models.CharField(choices=[('Member', 'Member'), ('Group', 'Group')], default='member', max_length=10, verbose_name='DB Location'),
        ),
        migrations.AlterField(
            model_name='dbconfiguration',
            name='recordNumber',
            field=models.IntegerField(default=0, verbose_name='Record Number'),
        ),
        migrations.AlterField(
            model_name='dbconfiguration',
            name='recordSize',
            field=models.IntegerField(default=0, verbose_name='Record Size (Byte)'),
        ),
        migrations.AlterField(
            model_name='dbconfiguration',
            name='subscriberNumber',
            field=models.IntegerField(default=0, verbose_name='Subscriber Number'),
        ),
        migrations.AlterField(
            model_name='dbconfiguration',
            name='todoLogSize',
            field=models.IntegerField(default=0, verbose_name='Todo Log Size (MB)'),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='cpuImpactPerRelease',
            field=models.FloatField(default=5, verbose_name='CPU Impact per Release (%)'),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='dbImpactPerRelease',
            field=models.FloatField(default=10, verbose_name='DB Impact per Release (%)'),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='memoryImpactPerRelease',
            field=models.FloatField(default=10, verbose_name='Memory Impact per Release (%)'),
        ),
    ]
