# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-14 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20180314_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinformation',
            name='dbCPUNumber',
            field=models.IntegerField(default=40, verbose_name='DB CPU Number'),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='dbMemory',
            field=models.IntegerField(default=105, verbose_name='DB Memory'),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='ioCPUNumber',
            field=models.IntegerField(default=16, verbose_name='IO CPU Number'),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='ioMemory',
            field=models.IntegerField(default=32, verbose_name='IO Memory'),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='mateCPUNumber',
            field=models.IntegerField(default=16, verbose_name='Mate CPU Number'),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='mateMemory',
            field=models.IntegerField(default=64, verbose_name='Mate Memory'),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='pilotCPUNumber',
            field=models.IntegerField(default=8, verbose_name='Pilot CPU Number'),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='pilotMemory',
            field=models.IntegerField(default=32, verbose_name='Pilot Memory'),
        ),
    ]
