# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20180321_1747'),
        ('project', '0015_auto_20180314_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbconfiguration',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.ApplicationName'),
            preserve_default=False,
        ),
    ]
