# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-27 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20180327_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinformation',
            name='dbCPUNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DB_CPU_Number', to='hardware.CPUList', verbose_name='DB CPU Number'),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='dbMemory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DB_Memory', to='hardware.MemoryList', verbose_name='DB Memory'),
        ),
    ]
