# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-29 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20180327_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationconfiguration',
            name='deployOption',
            field=models.CharField(choices=[('EPAY Node', 'EPAY Node'), ('DRouter Node', 'DRouter Node'), ('Group Node', 'Group Node'), ('CDR Pre-Processor Node', 'CDR Pre-Processor Node'), ('eCGS Node', 'eCGS Node'), ('NTGW Node', 'NTGW Node'), ('eCTRL Node', 'eCTRL Node'), ('EPPSM Node', 'EPPSM Node'), ('GRouter Node', 'GRouter Node')], max_length=30, verbose_name='Deploy Option'),
        ),
    ]
