# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20180329_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedresult',
            name='boundType',
            field=models.CharField(choices=[('CPU Bound', 'CPU Bound'), ('Memory Bound', 'Memory Bound')], default='CPU Bound', max_length=20, verbose_name='Bound Type'),
        ),
        migrations.AddField(
            model_name='calculatedresult',
            name='calCPUAppNumber',
            field=models.FloatField(default=0, verbose_name='Calculated CPU Based App Node Number'),
        ),
        migrations.AddField(
            model_name='calculatedresult',
            name='calDBNumber',
            field=models.FloatField(default=0, verbose_name='Calculated DB Node Number'),
        ),
        migrations.AddField(
            model_name='calculatedresult',
            name='calIONumber',
            field=models.FloatField(default=0, verbose_name='Calculated IO Node Number'),
        ),
        migrations.AddField(
            model_name='calculatedresult',
            name='calMemAppNumber',
            field=models.FloatField(default=0, verbose_name='Calculated Memory Based App Node Number'),
        ),
        migrations.AlterField(
            model_name='calculatedresult',
            name='appNodeNumber',
            field=models.IntegerField(default=0, verbose_name='App Node Number'),
        ),
        migrations.AlterField(
            model_name='calculatedresult',
            name='dbNodeNumber',
            field=models.IntegerField(default=0, verbose_name='DB Node Number'),
        ),
        migrations.AlterField(
            model_name='calculatedresult',
            name='ioNodeNumber',
            field=models.IntegerField(default=0, verbose_name='IO Node Number'),
        ),
    ]
