# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-17 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20180417_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedresult',
            name='systemNumber',
            field=models.IntegerField(default=0, verbose_name='System Number'),
        ),
    ]
