# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_applicationconfiguration_systemnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensioningresult',
            name='amaRecordNumberPerSecond',
            field=models.FloatField(default=0, verbose_name='AMA Record Number Per Second'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='amaRetrieveSpeed',
            field=models.FloatField(default=0, verbose_name='AMA Retrieve Speed (Byte/S)'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='appNodeMemoryUsagePercent',
            field=models.FloatField(default=0, verbose_name='App Node Memory Usage (%)'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='appNodeNeededNumber',
            field=models.IntegerField(default=0, verbose_name='APP Node Number'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='averageClientCPUUsage',
            field=models.FloatField(default=0, verbose_name='Needed APP Node Number'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='dbCacheSize',
            field=models.FloatField(default=0, verbose_name='DB Cache Size (MB)'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='dbDiskSizeForMateUpdate',
            field=models.FloatField(default=0, verbose_name='Disk Size For Mate Update (MB)'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='dbNodeNeededNumber',
            field=models.IntegerField(default=0, verbose_name='DB Node Number'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='dialyBillingFileSize',
            field=models.FloatField(default=0, verbose_name='Billing File Size Per Day (MB)'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='diskSizeForDB',
            field=models.FloatField(default=0, verbose_name='Disk Size For DB (MB)'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='ethernetPortsRequiredNumber',
            field=models.IntegerField(default=0, verbose_name='Ethernet Ports Required Number'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='ioNodeNeededNumber',
            field=models.IntegerField(default=0, verbose_name='IO Node Number'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='ladpDiameterUDP',
            field=models.FloatField(default=0, verbose_name='LDAP/Diameter Speed (Byte/S)'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='memoryUsagePerAppNode',
            field=models.FloatField(default=0, verbose_name='Memory Usage Per App Node (MB)'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='memoryUsagePerClient',
            field=models.FloatField(default=0, verbose_name='Memory Usage Per Client (MB)'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='muSpeed',
            field=models.FloatField(default=0, verbose_name='Mate Update Speed (Byte/S)'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='pilotNodeNeededNumber',
            field=models.IntegerField(default=0, verbose_name='Pilot Node Number'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='pilotSharedDiskSize',
            field=models.FloatField(default=0, verbose_name='Pilot Shared Disk Size (MB)'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='sigtranSpeed',
            field=models.FloatField(default=0, verbose_name='SIGTRAN Speed (Byte/S)'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='systemNumber',
            field=models.IntegerField(default=0, verbose_name='System Number'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='totalMemoryUsage',
            field=models.FloatField(default=0, verbose_name='Total Memory Usage (MB)'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='totalNodeNeededNumber',
            field=models.IntegerField(default=0, verbose_name='Total Node Number'),
        ),
        migrations.AlterField(
            model_name='dimensioningresult',
            name='totalTCPUDPSpeed',
            field=models.FloatField(default=0, verbose_name='Total TCP/UDP Speed (Byte/S)'),
        ),
    ]
