# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-24 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20180420_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensioningresult',
            name='mateNodeNeededNumber',
            field=models.IntegerField(default=0, verbose_name='Mate Node Number'),
        ),
    ]
