# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_release_trafficrequirededicatemate'),
        ('project', '0028_dimensioningresult_matenodeneedednumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimensioningresultpersystem',
            name='dimensioningResult',
        ),
        migrations.AddField(
            model_name='dimensioningresultpersystem',
            name='applicationName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.ApplicationName', verbose_name='Application Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimensioningresultpersystem',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimensioningresultpersystem',
            name='systemSequence',
            field=models.IntegerField(default=0),
        ),
    ]
