# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_dimensioningresultpersystem_matenodenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensioningresult',
            name='calculated_app_node_number',
            field=models.IntegerField(default=0),
        ),
    ]
