# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-09 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_auto_20180509_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinformation',
            name='groupAccountNumber',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Group Account'),
        ),
    ]
