# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-14 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_auto_20180509_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconfiguration',
            name='memberGroupOption',
            field=models.CharField(choices=[('Member', 'Member'), ('Group', 'Group')], default='Member', max_length=10, verbose_name='DB Location'),
        ),
        migrations.AlterField(
            model_name='dbconfiguration',
            name='referenceDBFactor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dbconfiguration',
            name='referencePlaceholderRatio',
            field=models.FloatField(default=0),
        ),
    ]
